logging:
  level:
    khtml.backend: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.http: DEBUG