jwt:
  secret: YWJjZGVmZ2hpams1NjM0MjEyMzQ1Njc4OTA5ODc2NTQzMjEyMzQ1Njc4OTBhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejEyMzQ1Njc4OTA5ODc2NTQzMjEyMzQ1Njc4OTA=
  access-token-expire-time: 1800000    # 30분 (1800초)
  refresh-token-expire-time: 1209600000 # 14일
  header: Authorization
  prefix: Bearer