spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: a7b1d97767e3ad9295ce072446cecdcc
            client-secret: mN2ONNQDAv83qGkATLxvgMGHjo0T6JAd
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
            client-authentication-method: none
          google:
            client-id: 607026141796-db8ueh97plmo7aoarcannvonpinbii0g.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-id: CNUIJsLrCw9Fo3riaLUp
            client-secret: TomLxKjLZR
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            scope:
              - name
              - profile
              - email
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: "https://nid.naver.com/oauth2.0/authorize"
            token-uri: "https://nid.naver.com/oauth2.0/token"
            user-info-uri: "https://openapi.naver.com/v1/nid/me"
            user-name-attribute: response